about_me/urls.py
from django.urls import path
from . import views
from django.conf.urls import url, include
from django.contrib import admin
from about_me import views

urlpatterns = [
    url(r'^about_me/$', views.about_me, name='about_me'),
]

gallery/urls.py
from django.urls import path
from . import views
from django.conf.urls import url, include
from django.contrib import admin
from gallery import views

urlpatterns = [
    url(r'^gallery/$', views.gallery, name='gallery'),
    url(r'^gallery/(?P<gallery_id>\w+)/$', views.galleries, name='galleries'),
]

landing/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from landing import views

urlpatterns = [


    url(r'^$', views.landing, name='landing'),

]

my_contact/urls.py
from django.urls import path
from . import views
from django.conf.urls import url, include
from django.contrib import admin
from my_contact import views

urlpatterns = [
    url(r'^my_contact/$', views.my_contact, name='my_contact'),

]

photographersite/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^', include('landing.urls')),
    url(r'^', include('gallery.urls')),
    url(r'^', include('about_me.urls')),
    url(r'^', include('my_contact.urls')),
] \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/models.py
from django.db import models


class GalleryCategory(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Категорія галереї'
        verbose_name_plural = 'Категорія галерей'


class Gallery(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    description = models.TextField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    category = models.ForeignKey(GalleryCategory, blank=True, null=True, default=None, on_delete=models.CASCADE)
    short_description = models.TextField(blank=True, null=True, default=None)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Галлерея'
        verbose_name_plural = 'Галлереї'


class GalleryImage(models.Model):
    gallery = models.ForeignKey(Gallery, blank=True, null=True, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='gallery_images/')
    is_main = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.id

    class Meta:
        verbose_name = 'Фотографія'
        verbose_name_plural = 'Фотографії'

landing/models.py
from django.db import models


class Subscriber(models.Model):

    call_number = models.CharField("Номер телефону",max_length=128)
    name = models.CharField("Ім'я", max_length=128)
    message = models.CharField('Повідомлення', max_length=128)
    event_date =models.CharField('Час та дата фотосесії', max_length=128)

    def __str__(self):
        return "Пользователь %s %s" % (self.name, self.call_number,)

    class Meta:
        verbose_name = 'Запит'
        verbose_name_plural = 'Запити на фотосесію'

gallery/forms.py
from django import forms
from .models import *

# class SubscriberForm(forms.ModelForm):
#
# 	class Meta:
# 		model = Subscriber
# 		exclude = [""]

landing/forms.py
from django import forms
from .models import *


class SubscriberForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        exclude = [""]

about_me/views.py
from django.shortcuts import render
# from .forms import SubscriberForm
from about_me.models import *

def about_me(request):
	# gallery_images = GalleryImage.objects.filter(is_active = True, is_main=True)
	return render(request, 'about_me/about_me.html', locals())

gallery/views.py
from django.shortcuts import render
# from .forms import SubscriberForm
from gallery.models import *

def gallery(request):
	gallery_images = GalleryImage.objects.filter(is_active = True, is_main=True)
	return render(request, 'galleries/gallery.html', locals())




def galleries(request, gallery_id):
    gallery_images = GalleryImage.objects.filter(is_active=True, is_main=True)
    gallery = Gallery.objects.get(id=gallery_id)

    session_key = request.session.session_key
    if not session_key:
        request.session.cycle_key()

    print(request.session.session_key)

    return render(request, 'galleries/photossession.html', locals())

landing/views.py
from django.shortcuts import render
from .forms import SubscriberForm




def landing(request):
    form = SubscriberForm(request.POST or None)

    if request.method == "POST" and form.is_valid():
        print(request.POST)
        print(form.cleaned_data)
        data = form.cleaned_data

        print (data['name'])

        form = form.save()

    return render(request, 'landing/landing.html', locals())

my_contact/views.py
from django.shortcuts import render
# from .forms import SubscriberForm
from my_contact.models import *

def my_contact(request):
	# gallery_images = GalleryImage.objects.filter(is_active = True, is_main=True)
	return render(request, 'my_contact/my_contact.html', locals())

templates/about_me/about_me.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="wpb_column vc_column_container vc_col-sm-8">
                <div class="vc_column-inner">
                    <div class="wpb_wrapper">
                        <div class="wpb_text_column wpb_content_element ">
                            <div class="wpb_wrapper">
                                <p><strong>About me</strong></p>
                                <p>&nbsp;</p>
                                <p>My interest in photography did not begin with books or mentors but evolved through a fascination of the natural world that shaped all parts of my life and brought them together. The desire, however, to communicate the way I felt about mountains and wild places began ironically, not on dry land but beneath the waves. With little photographic knowledge, I created a portfolio of images around Scotland’s coastline and in the Red Sea and was surprised to win ‘best newcomer to underwater photography’ in the <em>Camera Beneath the Waves</em> competition in 1981. Working at the time as an operations manager it was the catalyst that changed my life, and following a stint on a North Sea oil platform as a photo-technician, I was soon following a career as a professional photographer.
                                My interest in photography did not begin with books or mentors but evolved through a fascination of the natural world that shaped all parts of my life and brought them together. The desire, however, to communicate the way I felt about mountains and wild places began ironically, not on dry land but beneath the waves. With little photographic knowledge, I created a portfolio of images around Scotland’s coastline and in the Red Sea and was surprised to win ‘best newcomer to underwater photography’ in the
                                My interest in photography did not begin with books or mentors but evolved through a fascination of the natural world that shaped all parts of my life and brought them together. The desire, however, to communicate the way I felt about mountains and wild places began ironically, not on dry land but beneath the waves. With little photographic knowledge, I created a portfolio of images around Scotland’s coastline and in the Red Sea and was surprised to win ‘best newcomer to underwater photography’ in the
                                My interest in photography did not begin with books or mentors but evolved through a fascination of the natural world that shaped all parts of my life and brought them together. The desire, however, to communicate the way I felt about mountains and wild places began ironically, not on dry land but beneath the waves. With little photographic knowledge, I created a portfolio of images around Scotland’s coastline and in the Red Sea and was surprised to win ‘best newcomer to underwater photography’ in the
                                My interest in photography did not begin with books or mentors but evolved through a fascination of the natural world that shaped all parts of my life and brought them together. The desire, however, to communicate the way I felt about mountains and wild places began ironically, not on dry land but beneath the waves. With little photographic knowledge, I created a portfolio of images around Scotland’s coastline and in the Red Sea and was surprised to win ‘best newcomer to underwater photography’ in the
                                My interest in photography did not begin with books or mentors but evolved through a fascination of the natural world that shaped all parts of my life and brought them together. The desire, however, to communicate the way I felt about mountains and wild places began ironically, not on dry land but beneath the waves. With little photographic knowledge, I created a portfolio of images around Scotland’s coastline and in the Red Sea and was surprised to win ‘best newcomer to underwater photography’ in the
                                My interest in photography did not begin with books or mentors but evolved through a fascination of the natural world that shaped all parts of my life and brought them together. The desire, however, to communicate the way I felt about mountains and wild places began ironically, not on dry land but beneath the waves. With little photographic knowledge, I created a portfolio of images around Scotland’s coastline and in the Red Sea and was surprised to win ‘best newcomer to underwater photography’ in the
                                My interest in photography did not begin with books or mentors but evolved through a fascination of the natural world that shaped all parts of my life and brought them together. The desire, however, to communicate the way I felt about mountains and wild places began ironically, not on dry land but beneath the waves. With little photographic knowledge, I created a portfolio of images around Scotland’s coastline and in the Red Sea and was surprised to win ‘best newcomer to underwater photography’ in the
                                </p>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            </div>
            <div class="col-lg-3 offset-1">
                <div class="vc_row wpb_row section vc_row-fluid  grid_section" style=" padding-top:87px; padding-bottom:0px; text-align:left;">
    <div class=" section_inner clearfix">
        <div class="section_inner_margin clearfix">
            <div class="wpb_column vc_column_container vc_col-sm-4">
                <div class="vc_column-inner">
                    <div class="wpb_wrapper">
                        <div class="separator  transparent   " style="margin-top: 185px;"></div>
                            <div class="wpb_single_image wpb_content_element vc_align_right">
                                <div class="wpb_wrapper">
                                    <div class="vc_single_image-wrapper vc_box_shadow_3d  vc_box_border_grey"><span class="vc_box_shadow_3d_wrap">
                                        <img src="{% static 'images/3.jpg' %}" class="vc_single_image-img attachment-medium" alt=""  sizes="(max-width: 300px) 100vw, 300px" width="300" height="300"></span>
                                    </div>
                                </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
            </div>
        </div>
    </div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html class="wide wow-animation" lang="en">
  <head>
    <!-- Site Title-->
    <title>Home</title>
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
    <link rel="icon" href="{% static 'images/favicon.css' %}">

    <!-- Stylesheets-->
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lato:300,400,700,400italic%7CJosefin+Sans:400,700,300italic">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!--[if lt IE 10]>
    <div style="background: #212121; padding: 10px 0; box-shadow: 3px 3px 5px 0 rgba(0,0,0,.3); clear: both; text-align:center; position: relative; z-index:1;"><a href="http://windows.microsoft.com/en-US/internet-explorer/"><img src="images/ie8-panel/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."></a></div>
    <script src="js/html5shiv.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div id="page-loader">
      <div class="page-loader-body">
        <div class="cssload-spinner">
          <div class="cssload-cube cssload-cube0"></div>
          <div class="cssload-cube cssload-cube1"></div>
          <div class="cssload-cube cssload-cube2"></div>
          <div class="cssload-cube cssload-cube3"></div>
          <div class="cssload-cube cssload-cube4"></div>
          <div class="cssload-cube cssload-cube5"></div>
          <div class="cssload-cube cssload-cube6"></div>
          <div class="cssload-cube cssload-cube7"></div>
          <div class="cssload-cube cssload-cube8"></div>
          <div class="cssload-cube cssload-cube9"></div>
          <div class="cssload-cube cssload-cube10"></div>
          <div class="cssload-cube cssload-cube11"></div>
          <div class="cssload-cube cssload-cube12"></div>
          <div class="cssload-cube cssload-cube13"></div>
          <div class="cssload-cube cssload-cube14"></div>
          <div class="cssload-cube cssload-cube15"></div>
        </div>
      </div>
    </div>
    <!-- Page-->
    <div class="page">
      <!-- Page header-->
      <header class="section page-header">
        <!-- RD Navbar-->
        <div class="rd-navbar-wrap">
          <nav class="rd-navbar" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-sm-device-layout="rd-navbar-fixed" data-md-layout="rd-navbar-static" data-md-device-layout="rd-navbar-fixed" data-lg-device-layout="rd-navbar-static" data-lg-layout="rd-navbar-static" data-stick-up-clone="false" data-md-stick-up-offset="5px" data-lg-stick-up-offset="5px" data-md-stick-up="true" data-lg-stick-up="true">
            <div class="rd-navbar-main-outer">
              <div class="rd-navbar-main">
                <!-- RD Navbar Panel-->
                <div class="rd-navbar-panel">
                  <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav-wrap"><span></span></button>
                  <!-- RD Navbar Brand-->
                  <div class="rd-navbar-brand"><a class="brand" href="/">
                      <div class="brand__name"><img class="brand__logo-dark" src="{% static 'images/logo.jpg'%}" alt="" width="243" height="57"/><img class="brand__logo-light" src="{% static 'images/logo.jpg'%}" alt="" width="243" height="57"/>
                      </div></a></div>
                </div>
                <!-- RD Navbar Nav-->
                <div class="rd-navbar-nav-wrap">
                  <div class="rd-navbar-element">
                    <ul class="list-icons list-inline-sm">
                      <li><a target="_blank" class="icon icon-sm fa fa-instagram icon-style-camera" href="https://www.instagram.com/rivne_photo_bobrovska/"><span></span><span></span><span></span><span></span></a></li>
                      <li><a class="icon icon-sm fa fa-facebook icon-style-camera" href="#"><span></span><span></span><span></span><span></span></a></li>
                      <li><a class="icon icon-sm fa fa-pinterest icon-style-camera" href="#"><span></span><span></span><span></span><span></span></a></li>
                    </ul>
                  </div>
                  <!-- RD Navbar Nav-->
                  <ul class="rd-navbar-nav">
                    <li class="active"><a href="{% url 'landing' %}">Home</a>
                    </li>
                    <li><a href="{% url 'about_me' %}">Про мене</a>
                    </li>
                    <li><a href="{% url 'gallery' %}">Портфолiо</a>
                    </li>
                    <li><a href="{% url 'my_contact' %}">Мої контакти</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </header>
        {% block content %}
        {% endblock content %}

    </div>



      <footer class="footer-centered section bg-gray-darker">
        <div class="shell">
          <div class="range range-sm-center">
            <div class="cell-sm-10 cell-md-8 cell-lg-6">
              <!-- Brand-->
{#                <a class="brand" href="/">#}
{#                <div class="brand__name"><img src="{% static 'images/logo.jpg' %}" alt="" width="243" height="57"/>#}
{#                </div></a>#}
              <ul class="list-icons list-inline-sm">
                <li><a class="icon icon-sm fa fa-instagram icon-style-camera" href="#"><span></span><span></span><span></span><span></span></a></li>
                <li><a class="icon icon-sm fa fa-facebook icon-style-camera" href="#"><span></span><span></span><span></span><span></span></a></li>
                <li><a class="icon icon-sm fa fa-pinterest icon-style-camera" href="#"><span></span><span></span><span></span><span></span></a></li>
              </ul>
              <p class="rights"><span>&copy;&nbsp;</span><span class="copyright-year"></span>. All Rights Reserved. Design by <a href="https://www.templatemonster.com">TemplateMonster</a></p>
            </div>
          </div>
        </div>
      </footer>
    </div>
    <!-- Global Mailform Output-->
    <div class="snackbars" id="form-output-global"></div>
    <!-- Javascript-->
    <script src="{% static 'js/core.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>


    <!-- fancyBox CSS -->
    <link rel="stylesheet" href="{% static 'fancybox/dist/jquery.fancybox.min.css' %}">

    <!-- fancyBox JS -->
    <script src="{% static 'fancybox/dist/jquery.fancybox.min.js' %}"></script>
    <!-- coded by starlight-->

  </body>
</html>

templates/footer.html
<footer>
    <div>
        <h3>footer is here</h3>
    </div>
</footer>

templates/galleries/gallery.html
{% extends 'base.html' %}

{% block content %}

<div class="section section1">
  <div class="container">
    <div class="row">
      {% for gallery_image in gallery_images %}
      <div class="col-lg-3 isotope-item">
        <div class="product-item">
            <a href="{% url 'galleries' gallery_image.gallery.id %}">
              <img src="{{ gallery_image.image.url }}" alt="">
                <div class="thumb-ruby__caption">
              <p class="thumb-ruby__title heading-3">Beach Wedding</p>
               <p class="thumb-ruby__text">If you are looking for high quality wedding photography, I will be glad to help you.
                            <!-- Portfolio--></p>
           </div>
            </a>
            <div>
          </div>
          <h4>{{ gallery_image.gallery.name }}</h4>
          <p>
            {{gallery_image.gallery.description|truncatechars_html:20}}
          </p>
        </div>
      </div>
      {% endfor %}
    </div>

  </div>
</div>



{% endblock %}

{# <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item">#}
{#     <a class="thumb-ruby thumb-mixed_height-2 thumb-mixed_md" href="{% static 'images/3.jpg'%}" data-lightgallery="item">#}
{#         <img class="thumb-ruby__image" src="{% static 'images/3.jpg'%}" alt="" width="440" height="327"/>#}
{#           <div class="thumb-ruby__caption">#}
{#              <p class="thumb-ruby__title heading-3">Beach Wedding</p>#}
{#               <p class="thumb-ruby__text">If you are looking for high quality wedding photography, I will be glad to help you.#}
{#                            <!-- Portfolio--></p>#}
{#           </div>#}
{#     </a>#}
{#              </div>#}

templates/galleries/photossession.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container">
        <div class="row">

            {% for image_item in gallery.galleryimage_set.all %}
                <div class="col-lg-3 col-md-4 col-6 thumb">
                    <div class="product-item">
                        <a data-fancybox="gallery" href="{{ image_item.image.url }}" >
                            <img class="img-fluid" src="{{ image_item.image.url }}" alt="">
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/my_contact/my_contact.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
          <!-- Get in Touch-->
      <section class="section section-md bg-white text-center">
        <div class="shell">
          <div class="range range-md-center">
            <div class="cell-md-11 cell-lg-10">
              <h2 class="text-bold">Get in Touch</h2>
              <p><span class="box-width-2">I am available 24/7 by fax, e-mail or by phone. You can also use a quick contact form to ask a question about my services.</span></p>
              <div class="layout-columns">
                <div class="layout-columns__main">
                  <div class="layout-columns__main-inner">
                    <!-- RD Mailform-->
                    <form class="rd-mailform" data-form-output="form-output-global" data-form-type="contact" method="POST">{% csrf_token %}
                          <div class="form-group">
                          <input class="form-input" id="contact-date" type="text" data-time-picker="date" name="{{ form.event_date.name }}" data-constraints="@Required">
                          <label class="form-label" for="contact-date">Дата події</label>
                        </div>

                        <div class="form-wrap">
                          <input class="form-input" id="contact-name" type="text" name="{{ form.name.name}}" data-constraints="@Required">
                          <label class="form-label" for="contact-name">Ваше ім'я</label>
                        </div>
                        <div class="form-wrap">
                          <input class="form-input"  id="contact-phone" type="text" name="{{ form.call_number.name}}" data-constraints="@Required">
                          <label class="form-label" for="contact-phone">Номер телефону</label>
                        </div>

                        <div class="form-wrap">
                          <label class="form-label" for="contact-message">Ваше повідомлення</label>
                          <textarea class="form-input" id="contact-message" name="{{ form.message.name}}" data-constraints="@Required"></textarea>
                        </div>


                        <div class="form-wrap form-button offset-1">
                          <button class="button button-block button-primary-outline button-ujarak" type="submit">замовити</button>
                        </div>
                      </form>
                  </div>
                </div>
                <div class="layout-columns__aside">
                  <div class="layout-columns__aside-item">
                    <p class="heading-5">Socials</p>
                    <div class="divider-modern"></div>
                    <ul class="list-inline-xs">
                      <li><a class="icon icon-md icon-gray-7 fa fa-facebook" href="#"></a></li>
                      <li><a class="icon icon-md icon-gray-7 fa fa-twitter" href="#"></a></li>
                      <li><a class="icon icon-md icon-gray-7 fa fa-google" href="#"></a></li>
                      <li><a class="icon icon-md icon-gray-7 fa fa-youtube" href="#"></a></li>
                    </ul>
                  </div>
                  <div class="layout-columns__aside-item">
                    <p class="heading-5">Мій номер</p>
                    <div class="divider-modern"></div>
                    <div class="unit unit-horizontal unit-spacing-xxs">
                      <div class="unit__left"><span class="icon icon-md icon-primary material-icons-local_phone"></span></div>
                      <div class="unit__body"><a href="tel:#">1-800-1234-567</a></div>
                    </div>
                  </div>
                  <div class="layout-columns__aside-item">
                    <p class="heading-5">Address</p>
                    <div class="divider-modern"></div>
                    <div class="unit unit-horizontal unit-spacing-xxs">
                      <div class="unit__left"><span class="icon icon-md icon-primary material-icons-location_on"></span></div>
                      <div class="unit__body"><a href="#">267 Park Avenue New York, NY 90210</a></div>
                    </div>
                  </div>
                  <div class="layout-columns__aside-item">
                    <p class="heading-5">opening hours</p>
                    <div class="divider-modern"></div>
                    <div class="unit unit-horizontal unit-spacing-xxs">
                      <div class="unit__left"><span class="icon icon-md icon-primary mdi mdi-clock"></span></div>
                      <div class="unit__body"><span>I work every day 9:00–23:00</span></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
{% endblock %}

templates/navbar.html
<div id="page-loader">
      <div class="page-loader-body">
        <div class="cssload-spinner">
          <div class="cssload-cube cssload-cube0"></div>
          <div class="cssload-cube cssload-cube1"></div>
          <div class="cssload-cube cssload-cube2"></div>
          <div class="cssload-cube cssload-cube3"></div>
          <div class="cssload-cube cssload-cube4"></div>
          <div class="cssload-cube cssload-cube5"></div>
          <div class="cssload-cube cssload-cube6"></div>
          <div class="cssload-cube cssload-cube7"></div>
          <div class="cssload-cube cssload-cube8"></div>
          <div class="cssload-cube cssload-cube9"></div>
          <div class="cssload-cube cssload-cube10"></div>
          <div class="cssload-cube cssload-cube11"></div>
          <div class="cssload-cube cssload-cube12"></div>
          <div class="cssload-cube cssload-cube13"></div>
          <div class="cssload-cube cssload-cube14"></div>
          <div class="cssload-cube cssload-cube15"></div>
        </div>
      </div>
    </div>
    <!-- Page-->
    <div class="page">
      <!-- Page header-->
      <header class="section page-header">
        <!-- RD Navbar-->
        <div class="rd-navbar-wrap">
          <nav class="rd-navbar" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-sm-device-layout="rd-navbar-fixed" data-md-layout="rd-navbar-static" data-md-device-layout="rd-navbar-fixed" data-lg-device-layout="rd-navbar-static" data-lg-layout="rd-navbar-static" data-stick-up-clone="false" data-md-stick-up-offset="5px" data-lg-stick-up-offset="5px" data-md-stick-up="true" data-lg-stick-up="true">
            <div class="rd-navbar-main-outer">
              <div class="rd-navbar-main">
                <!-- RD Navbar Panel-->
                <div class="rd-navbar-panel">
                  <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav-wrap"><span></span></button>
                  <!-- RD Navbar Brand-->
                  <div class="rd-navbar-brand"><a class="brand" href="index.html">
                      <div class="brand__name"><img class="brand__logo-dark" src="{% static 'images/logo-243x57.png'%}" alt="" width="243" height="57"/><img class="brand__logo-light" src="{% static 'images/logo-inverse-243x57.png'%}" alt="" width="243" height="57"/>
                      </div></a></div>
                </div>
                <!-- RD Navbar Nav-->
                <div class="rd-navbar-nav-wrap">
                  <div class="rd-navbar-element">
                    <ul class="list-icons list-inline-sm">
                      <li><a class="icon icon-sm fa fa-instagram icon-style-camera" href="#"><span></span><span></span><span></span><span></span></a></li>
                      <li><a class="icon icon-sm fa fa-facebook icon-style-camera" href="#"><span></span><span></span><span></span><span></span></a></li>
                      <li><a class="icon icon-sm fa fa-pinterest icon-style-camera" href="#"><span></span><span></span><span></span><span></span></a></li>
                    </ul>
                  </div>
                  <!-- RD Navbar Nav-->
                  <ul class="rd-navbar-nav">
                    <li class="active"><a href="index.html">Home</a>
                    </li>
                    <li><a href="about-me.html">Про мене</a>
                    </li>
                    <li><a href="typography.html">Портфолiо</a>
                    </li>
                    <li><a href="contact-me.html">Мої контакти</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </header>